### ISSUE TITLE
[FileNotFoundError] No such file or directory

### ISSUE THREAD

**Issue by cacadosman** [eiji98/CTFdScraper#1]
**Expected:**
- System should create a directory with special characters.
- System read a file/directory with special characters.

**Actual:**
- System create a directory without special characters.
- System read a file/directory with special characters and causing FileNotFoundError.

**Suggestions**
- System should create a directory with escaped strings.
- System read a file/directory with escaped strings.

**How to reproduce**
- System scrap a platform with challenges that have special characters

![error](https://user-images.githubusercontent.com/22091369/74599523-f5b7fd80-50b5-11ea-987a-de42729d057c.png)

**Comment by hanasuru** [comment]
Let met check it. Thanks

**Comment by cacadosman** [comment]
DONE
